server:
  port: 8086


spring:
  application:
     name : employee-services
  datasource:
    url : ${employeeDataSource}
    username : ${employeeDataSourceUserName}
    password : ${employeeDataSourcePassword}
    testWhileIdle : true
    validationQuery : SELECT 1
    max-active: 20
    max-idle: 10
    min-idle: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
security:
  basic:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/